export const degrees = [
  "B.Tech Computer Science and Engineering (CSE)",
  "B.Tech Artificial Intelligence and Machine Learning (AI & ML)",
  "B.Tech Data Science",
  "B.Tech Information Technology (IT)",
  "B.Tech Electronics and Communication Engineering (ECE)",
  "B.Tech Electrical Engineering (EE)",
  "B.Tech Mechanical Engineering",
  "B.Tech Civil Engineering",
  "B.Tech Chemical Engineering",
  "B.Tech Biotechnology",
  "B.Tech Aerospace Engineering",
  "B.Tech Robotics and Automation",
  "B.Tech Internet of Things (IoT)",
  "B.Tech Cyber Security",
  "B.Tech Cloud Computing",
  "B.Tech Blockchain Technology",

  "B.E. Computer Engineering",
  "B.E. Information Technology",
  "B.E. Mechanical Engineering",
  "B.E. Civil Engineering",
  "B.E. Electrical Engineering",
  "B.E. Electronics Engineering",

  "BCA (Bachelor of Computer Applications)",
  "B.Sc Computer Science",
  "B.Sc Information Technology",
  "B.Sc Data Science",
  "B.Sc Artificial Intelligence",
  "B.Sc Mathematics",
  "B.Sc Physics",
  "B.Sc Chemistry",

  "M.Tech Computer Science and Engineering",
  "M.Tech Artificial Intelligence",
  "M.Tech Data Science",
  "M.Tech Cyber Security",
  "M.Tech Machine Learning",

  "MCA (Master of Computer Applications)",
  "M.Sc Computer Science",
  "M.Sc Data Science",
  "MBA",
  "MBA Finance",
  "MBA Marketing",
  "MBA Human Resources",
  "MBA Business Analytics",

  "PhD Computer Science",
  "PhD Artificial Intelligence",
  "PhD Data Science"
];