export const roles = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Software Engineer",
  "Java Developer",
  "Python Developer",
  "React Developer",
  "Node.js Developer",
  "Android Developer",
  "iOS Developer",
  "Mobile App Developer",
  "Data Analyst",
  "Business Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Site Reliability Engineer",
  "Cyber Security Analyst",
  "Security Engineer",
  "Network Engineer",
  "System Administrator",
  "Database Administrator",
  "QA Engineer",
  "Automation Test Engineer",
  "Performance Test Engineer",
  "UI Designer",
  "UX Designer",
  "UI/UX Designer",
  "Product Manager",
  "Project Manager",
  "Program Manager",
  "Technical Lead",
  "Engineering Manager",
  "Scrum Master",
  "Solution Architect",
  "Cloud Architect",
  "Enterprise Architect",
  "Blockchain Developer",
  "Game Developer",
  "AR/VR Developer",
  "Embedded Systems Engineer",
  "IoT Engineer",
  "SAP Consultant",
  "Salesforce Developer",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Content Writer",
  "Technical Writer",
  "HR Executive",
  "Talent Acquisition Specialist",
  "Recruiter",
  "Financial Analyst",
  "Investment Analyst",
  "Accountant",
  "Operations Manager",
  "Customer Success Manager",
  "Support Engineer"
];